name: Create Directory on Push

on:
  push:
    branches: [ main ]

jobs:
  create_directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir ~/hi/
          echo "${{ secrets.RHY_SSH_PRIVATE_KEY }}" > ~/.ssh/pr_key