name: Create Directory on Push

on:
  push:
    branches: [ main ]

jobs:
  create_directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Configure SSH
        run: echo "${{ secrets.RHY_SSH_PRIVATE_KEY }}" > ~/.ssh/pr_key
