name: Pull GitHub Repository Contents

on:
  push:
    branches: [main]

jobs:
  pull_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      
      - name: Write private key to file
        run: echo "${{ secrets.RHY_SSH_PRIVATE_KEY }}" > ~/.ssh/RHY.pem
      
      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/RHY.pem
      
      - name: Update known_hosts file
        run: ssh-keyscan -H 3.124.195.133 >> ~/.ssh/known_hosts
      
      - name: SSH into Ubuntu machine and pull repository
        run: |
          ssh -i ~/.ssh/RHY.pem ubuntu@3.124.195.133 '
            mkdir -p ~/django_Project &&
            cd ~/django_Project &&
            git clone --filter=blob:none --sparse <repository_url> . &&
            git sparse-checkout init &&
            git sparse-checkout set !.github'
