name: Pull GitHub Repository Contents

on:
  push:
    branches: [main]

jobs:
  pull_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      
      - name: Write private key to file
        run: echo "${{ secrets.RHY_SSH_PRIVATE_KEY }}" > ~/.ssh/RHY.pem
      
      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/RHY.pem
      
      - name: Update known_hosts file
        run: ssh-keyscan -H 3.124.195.133 >> ~/.ssh/known_hosts
      
      - name: Check if directory exists
        run: |
          ssh -i ~/.ssh/RHY.pem ubuntu@3.124.195.133 'test -d ~/django_Project || echo "Directory not found"'
      
      - name: Clone or pull repository
        run: |
          ssh -i ~/.ssh/RHY.pem ubuntu@3.124.195.133 '
            if [ -d "~/django_Project" ]; then
              cd ~/django_Project
              if [ -z "$(ls -A .)" ]; then
                echo "Directory is empty"
                git pull origin main
              else
                echo "Directory is not empty"
                git pull origin main
              fi
            else
              echo "Creating directory"
              mkdir -p ~/django_Project &&
              cd ~/django_Project &&
              git clone https://github.com/RiyadM44/FinalPSampleTemplate.git .
            fi'
