name: SSH into Ubuntu Machine and Create Directory

on:
  push:
    branches: [main]

jobs:
  ssh_to_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      
      - name: Write private key to file
        run: echo "${{ secrets.RHY_SSH_PRIVATE_KEY }}" > ~/.ssh/RHY.pem
      
      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/RHY.pem
      
      - name: Update known_hosts file
        run: ssh-keyscan -H 3.124.195.133 >> ~/.ssh/known_hosts
      
      - name: SSH into Ubuntu machine and create directory
        run: ssh -i ~/.ssh/RHY.pem ubuntu@3.124.195.133 'mkdir -p ~/hi'
 